- hosts: all
  become: true
  tasks:
    - name: install apache2 Debian
      apt: name=apache2 state=present update_cache=yes
      when: ansible_os_family == "Debian"

    - name: apache2 start Debian
      service: name=apache2 state=started enabled=yes
      when: ansible_os_family == "Debian"

    - name: install httpd RedHat
      yum: name=httpd state=present update_cache=yes
      when: ansible_os_family == "RedHat"

    - name: httpd start RedHat
      service: name=httpd state=started enabled=yes
      when: ansible_os_family == "RedHat"
